#!/usr/bin/env bash
# batch_workflow.sh — End-to-end workflow: create input → batch fetch → validate
#
# Usage: bash examples/batch_workflow.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TMPDIR=$(mktemp -d)

echo "=== Batch Workflow Demo ==="
echo "Working directory: $TMPDIR"
echo ""

# Step 1: Create a sample input file with LeetCode URLs
cat > "$TMPDIR/sample_urls.md" << 'EOF'
# Sample Problem List

| Problem | Link |
|---------|------|
| Two Sum | https://leetcode.com/problems/two-sum/ |
| Valid Parentheses | https://leetcode.com/problems/valid-parentheses/ |
| Merge Intervals | https://leetcode.com/problems/merge-intervals/ |
EOF

echo "1. Created sample input file with 3 LeetCode URLs"
echo ""

# Step 2: Run batch fetch
echo "2. Running batch fetch..."
echo "   Command: node scripts/fetch_batch.js $TMPDIR/sample_urls.md"
echo ""
node "$SCRIPT_DIR/scripts/fetch_batch.js" "$TMPDIR/sample_urls.md" > "$TMPDIR/problems.json"
echo ""

# Step 3: Assemble the full track JSON
echo "3. Assembling track JSON..."
node -e "
const problems = JSON.parse(require('fs').readFileSync('$TMPDIR/problems.json', 'utf-8'));
const track = {
  title: 'Demo Track',
  description: 'A small demo track generated by the batch workflow.',
  order: 99,
  problems: problems
};
require('fs').writeFileSync('$TMPDIR/track.json', JSON.stringify(track, null, 2));
console.log('   Track assembled with ' + problems.length + ' problems.');
"
echo ""

# Step 4: Validate
echo "4. Validating track..."
echo "   Command: node scripts/validate_track.js $TMPDIR/track.json"
echo ""
node "$SCRIPT_DIR/scripts/validate_track.js" "$TMPDIR/track.json"

# Cleanup
rm -rf "$TMPDIR"
echo ""
echo "=== Workflow Complete ==="
